In [1]:
# 텐서 플로우 설치
# 아나콘다에서 설치 2분쯤 걸림. 
# !pip install tensorflow 
# 파이썬 터미널에서 설치
# pip install tensorflow

In [2]:
리스트1 = [1, 2, 3]
리스트2 = [[4], [5], [6]]
리스트3 = [7, 8, 9]
print(리스트1 + 리스트3) # 리스트1과 리스트3의 각 항이 더해지기를 기대했지만 ...
# 행렬곱 (1x3)행렬과 (3x1)행렬을 행렬곱하면 (1x1) 결과가 나옴
# 리스트1과 리스트2를 행렬곱 결과를 확인하려면...
행렬곱 = (리스트1[0] * 리스트2[0][0] + 리스트1[1] * 리스트2[1][0] + 리스트1[2] * 리스트2[2][0])
print(행렬곱)

[1, 2, 3, 7, 8, 9]
32


In [3]:
# 텐서 : 수학적으로 3차원 이상의 행렬을 의미
# 0차원 : 스칼라, 1차원 : 벡터, 2차원 : 행렬, 3차원이상 : 텐서
# 텐서 만들기
# 1. 상수
import tensorflow as tf
텐서1 = tf.constant([1,2,3])
텐서2 = tf.constant([[4],[5],[6]])
텐서3 = tf.constant([7,8,9])

In [4]:
# 산술연산 가능
print(텐서1 + 텐서3) # -, *, / 다 가능
print(tf.add(텐서1, 텐서3))
print(tf.subtract(텐서1, 텐서3))
print(tf.multiply(텐서1, 텐서3))
print(tf.divide(텐서1, 텐서3))

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([-6 -6 -6], shape=(3,), dtype=int32)
tf.Tensor([ 7 16 27], shape=(3,), dtype=int32)
tf.Tensor([0.14285714 0.25       0.33333333], shape=(3,), dtype=float64)


In [5]:
# 텐서1과 텐서2를 행렬곱하기 위해 텐서1의 행렬을 맞추는 작업
# 텐서1은 벡터
텐서1_reshape = tf.reshape(텐서1, (1,-1)) # 텐서2(3x1행렬)과 곱하기 위해서 1x3행렬로 변환
텐서1_reshape.shape

TensorShape([1, 3])

In [6]:
# 텐서1 행렬곱 텐서2
print(tf.matmul(텐서1_reshape, 텐서2))

tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [7]:
# 변수 선언하기 => 가중치 w1,w2
w = tf.Variable([3,2,1])
w

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

In [8]:
# 변수값 수정
w.assign([1,2,3])
# w = [1,2,3] # 안됨 리스트로 덮어쓰기 됨
w

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:
# 0으로 채워진 텐서 만들기
제로텐서 = tf.zeros([4, 2, 3]) # 4페이지 2줄 3글자
제로텐서

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [10]:
x = tf.Variable(3.0) # x = 3
# 기울기 구하기 y=x^2 함수에서 x가 3일 때 기울기를 구함
# y=x^2의 기울기함수는 y=2x(x^2을 미분하면)
with tf.GradientTape() as tape:
	y = x ** 2

dy_dx = tape.gradient(y, x)
print(dy_dx.numpy())

6.0
